import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import React from "react";
import NavBar from "./components/NavBar";
import Logos from "./components/Logos";
import Footer from "./components/Footer";
import {theme} from "./styles/theme";
import { CssBaseline, ThemeProvider } from "@mui/material";

export const metadata: Metadata = {
  title: "Proyecto Hídrico",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <CssBaseline/>
          <Logos/>
          <NavBar/>
          {children}
          <Footer/>
        </ThemeProvider>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
